LIGAR_LED:
    RCALL OBTER_RESULTADO
	RCALL DECODIFICADOR_NUMERO_COR
	RCALL EXIBIR_COR
	RET

OBTER_RESULTADO:
    MUL GANHADOR_DEZENA, SALTO_DEZENAS
    MOV RESULTADO_COR, R0
    ADD RESULTADO_COR, GANHADOR_UNIDADE
    RET

DECODIFICADOR_NUMERO_COR:
	LDI ZH, HIGH(TABELA_CORES << 1)
	LDI ZL, LOW (TABELA_CORES << 1)
	ADD ZL, RESULTADO_COR
	CLR R5
	ADC ZH, R5
	RET

EXIBIR_COR:
    RCALL DESLIGA_LEDS
	RCALL DECODIFICADOR_COR_LED
	RET

DECODIFICADOR_COR_LED:
	LPM R0, Z
	MOV R19, R0
	CPI R19,1
    BREQ acende_branco
    CPI R19,2
    BREQ acende_verde
    CPI R19,3
    BREQ acende_vermelho
    CLR RESULTADO_COR
	RET
	acende_branco:
		SBI PORTC, LED_BRANCO
		RET
	acende_verde:
		SBI PORTC, LED_VERDE
		RET
	acende_vermelho:
		SBI PORTC, LED_VERMELHO
		RET

DESLIGA_LEDS:
	CBI PORTC, LED_BRANCO
    CBI PORTC, LED_VERDE
    CBI PORTC, LED_VERMELHO
	RET

TABELA_CORES: .db 2, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 1, 3, 1, 3, 1, 3, 1, 3, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 1, 3, 1, 3, 1, 3, 1, 3, 0