start_sort:
    PUSH GANHADOR_UNIDADE
    PUSH GANHADOR_DEZENA
    LDI GANHADOR_UNIDADE, 0xFF
    LDI GANHADOR_DEZENA, 0x00
    RCALL loop_sort
    POP GANHADOR_DEZENA
    POP GANHADOR_UNIDADE

loop_sort:
    CMP GANHADOR_UNIDADE, 0x0F
    BRNE inc
    CMP GANHADOR_DEZENA, 0x03
    BRNE incre
    CMP GANHADOR_UNIDADE, 0x07
    BRNE inc
    RJMP zerar

inc:
    INC GANHADOR_UNIDADE
    RJMP loop_sort

incre:
    INC GANHADOR_DEZENA
    LDI GANHADOR_UNIDADE, 0xFF
    RJMP loop_sort

zerar:
    LDI RGANHADOR_UNIDADE, 0xFF
    RJMP loop_sort


    




